# Gitpod configuration for AWS Examples project
# This will automatically install AWS CLI when the workspace starts

image:
  file: .devcontainer/Dockerfile

tasks:
  - name: Install AWS CLI
    init: |
      # Download and install AWS CLI
      curl 'https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip' -o 'awscliv2.zip'
      unzip awscliv2.zip
      sudo ./aws/install
      
      # Clean up installation files
      rm -rf aws awscliv2.zip
      
      echo "AWS CLI installation completed!"
    command: |
      # Verify AWS CLI is installed
      aws --version
      echo "Workspace is ready!"

# VS Code extensions (optional)
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode